### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by RealSosiso4ka** [mrwan200/EnkaNetwork.py#13]
After updating to version `1.2.10dev0` I get `Unclosed client session` warning every time when requesting user data (.fetch_user() function).

**Comment by staciax** [comment]
can i see your code.

**Comment by RealSosiso4ka** [comment]
> can i see your code.



```
...
client = GenshinFunctions.enka_login("en")
user = await client.fetch_user(709666671)
```

GenshinFunctions.py:
```
def enka_login(language: str):
    return EnkaNetworkAPI(language, debug=False)
```

**Comment by RealSosiso4ka** [comment]
Oops, I should have done it a little differently...
```
client = GenshinFunctions.Basic.enka_login("en")
async with client:
    user = await client.fetch_user(709666671)
```

Forgive me for my stupidity...
