### ISSUE TITLE
[enhancement] Use httpx instead of aiohttp

### ISSUE THREAD

**Issue by rushkii** [mrwan200/EnkaNetwork.py#17]
httpx is the async of the requests version, the function is same as requests but it has async and the performance is much better than aiohttp.

If you want to save session to variable then:
```py
import httpx
import asyncio

async def main():
    ses = httpx.AsyncClient()

    async with ses:
        res = await ses.get("")
        print(res.json())

asyncio.run(main())
```

**Comment by mrwan200** [comment]
Hello
First thing I'm very sorry for reply late :(
So very busy homework in university

I'm not sure about `httpx` library is a better than `aiohttp` or not. After I check `httpx` library benchmark in website. It's so very confused about test benchmark.

Can you find some benchmark `httpx` library?

![Sorry](https://media.tenor.com/jyy9P99xD1oAAAAC/genshin-impact-genshin.gif)

**Comment by rushkii** [comment]
> Hello First thing I'm very sorry for reply late :( So very busy homework in university
> 
> I'm not sure about `httpx` library is a better than `aiohttp` or not. After I check `httpx` library benchmark in website. It's so very confused about test benchmark.
> 
> Can you find some benchmark `httpx` library?
> 
> ![Sorry](https://camo.githubusercontent.com/a564740212b1982bb23d8a064b960591f68c16c26c6639d532e6f770094679f6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6a7979395039397844316f41414141432f67656e7368696e2d696d706163742d67656e7368696e2e676966) [ ![Sorry](https://camo.githubusercontent.com/a564740212b1982bb23d8a064b960591f68c16c26c6639d532e6f770094679f6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6a7979395039397844316f41414141432f67656e7368696e2d696d706163742d67656e7368696e2e676966) ](https://camo.githubusercontent.com/a564740212b1982bb23d8a064b960591f68c16c26c6639d532e6f770094679f6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6a7979395039397844316f41414141432f67656e7368696e2d696d706163742d67656e7368696e2e676966) [ ](https://camo.githubusercontent.com/a564740212b1982bb23d8a064b960591f68c16c26c6639d532e6f770094679f6/68747470733a2f2f6d656469612e74656e6f722e636f6d2f6a7979395039397844316f41414141432f67656e7368696e2d696d706163742d67656e7368696e2e676966)

Ah, right. I think it's more faster with aiohttp instead
