### ISSUE TITLE
Update your data

### ISSUE THREAD

**Issue by DEViantUA** [mrwan200/EnkaNetwork.py#18]
ERROR:enkanetwork.assets:Character not found with id: 10000071
ERROR:enkanetwork.assets:Character not found with id: 10000072
ERROR:enkanetwork.assets:Namecards not found with id: 210133
ERROR:enkanetwork.assets:Character not found with id: 10000071
ERROR:enkanetwork.assets:Character not found with id: 10000072

**Comment by mrwan200** [comment]
Hello

What you install library from `pypi` or `GitHub`

If you install from `pypi` You must use code this to update:
https://github.com/mrwan200/EnkaNetwork.py/blob/master/example/update_assets.py

**Comment by DEViantUA** [comment]
> Hello
> 
> What you install library from `pypi` or `GitHub`
> 
> If you install from `pypi` You must use code this to update: https://github.com/mrwan200/EnkaNetwork.py/blob/master/example/update_assets.py

Ah, I understand, thanks.
