### ISSUE TITLE
Error on Cyno Assets

### ISSUE THREAD

**Issue by BlazingBots** [mrwan200/EnkaNetwork.py#19]
I got this error while trying to access the data of my cyno.

ERROR:enkanetwork.assets:Character not found with id: 10000071
ERROR:enkanetwork.assets:nameTextMapHash 1470442731 not found with language: EN
ERROR:enkanetwork.assets:Character not found with id: 10000071
ERROR:enkanetwork.assets:Character not found with id: 10000071
ERROR:enkanetwork.assets:nameTextMapHash 1470442731 not found with language: EN
ERROR:enkanetwork.assets:Character not found with id: 10000071

**Comment by BlazingBots** [comment]
Github tho, Alr, let me give me another try

**Comment by BlazingBots** [comment]
> Hello Where did you install the library from? `Pypi` or `GitHub`
> 
> If you install from `Pypi` You must be update assets from code this: https://github.com/mrwan200/EnkaNetwork.py/blob/master/example/update_assets.py

Still getting error with git. Can you check pls ? I might be wrong

**Comment by mrwan200** [comment]
Hm.. Hold a seconds I will check this issues

**Comment by mrwan200** [comment]
Sure. Here my discord ID: M-307

**Comment by BlazingBots** [comment]
After clearing the cache and re-installing the whole package the issue got resolved. I think I might be using the old version earlierI guess, closing the issue.
