### ISSUE TITLE
Validation error when trying to get data from a user with no signature

### ISSUE THREAD

**Issue by rhapsodya** [mrwan200/EnkaNetwork.py#2]
I got this error when I tried to get data from a user with no signature:

`1 validation error for EnkaNetworkResponse\nplayerInfo -> signature\n  field required (type=value_error.missing)`

I could temporarily fix this by removing the line `signature: str` from `enkanetwork/model/players.py`, but with this change, I can't get signature data from those who have it.

**Comment by mrwan200** [comment]
Fixed https://github.com/mrwan200/EnkaNetwork.py/compare/74c59c7b2c98...397f10b8bd35

Please reinstall `pip install enkanetwork.py` and you new see feature and fixed bug 😊
