### ISSUE TITLE
nilou issue

### ISSUE THREAD

**Issue by CUSTOMFAIL** [mrwan200/EnkaNetwork.py#20]
there is a issue in character.name of nilou

i have set nilou on display on my id 

when i run :

async def main():
    async with client:
        data = await client.fetch_user(849166888)
        print("=== Characters ===")
        for character in data.characters:
            print(f"ID: {character.id}")
            print(f"Name: {character.name}")

asyncio.run(main())

the results comes :

=== Characters ===
ID: 10000037
Name: Ganyu
ID: 10000022
Name: Venti
ID: 10000030
Name: Zhongli
ID: 10000052
Name: Raiden Shogun
ID: 10000070
Name: 
ID: 10000058
Name: Yae Miko
ID: 10000026
Name: Xiao
ID: 10000032
Name: Bennett

as you can see nilou name is ""
the error is:  ERROR:enkanetwork.assets:Character not found with id: 10000070

**Comment by mrwan200** [comment]
What you install library from `pypi` or `GitHub`

If you install library from `PyPi`. You must update assets from example this:
```py
import asyncio

from enkanetwork import EnkaNetworkAPI

client = EnkaNetworkAPI(debug=True)

async def main():
    async with client:
        await client.update_assets()
        # You can see the progress download new assets in console

asyncio.run(main())
```

**Comment by CUSTOMFAIL** [comment]
Thanks for helping.
