### ISSUE TITLE
Lib?

### ISSUE THREAD

**Issue by CUSTOMFAIL** [mrwan200/EnkaNetwork.py#27]
Enka network api did some changes and now it's problem for other repo 

https://github.com/EnkaNetwork/API-docs/commit/56cabc58909fe896c0a8984b07a66aa97c5541a9

**Comment by mrwan200** [comment]
I'm doing in branch https://github.com/mrwan200/EnkaNetwork.py/tree/new_feature because new version made my library so messy. 

But I will release new version soon tho
