### ISSUE TITLE
Invalid element name

### ISSUE THREAD

**Issue by RealSosiso4ka** [mrwan200/EnkaNetwork.py#3]
I think the name of element [here](https://github.com/mrwan200/EnkaNetwork.py/blob/master/enkanetwork/enum.py), line `36` must be «Cryo» and not «Cyro».

**Comment by mrwan200** [comment]
Fixed: https://github.com/mrwan200/EnkaNetwork.py/commit/6bbf42c7f02792ff4e981ffe89e79e23e9d467d5
