### ISSUE TITLE
There is no exception corresponding to status code 502.

### ISSUE THREAD

**Issue by karakoo** [mrwan200/EnkaNetwork.py#31]
https://github.com/mrwan200/EnkaNetwork.py/blob/ddfff47d4b9f7e35dfd6c97b5f01dae53ce8d212/enkanetwork/exception.py#L31-L38

So when `enka.network` returns a 502 status code, `KeyError` will be raised.

```python3
-----Traceback info-----
Traceback (most recent call last):
.....
  File "/root/Projects/Bot/plugins/genshin/player_cards.py", line 121, in player_cards
    data = await self._fetch_user(uid)
  File "/root/Projects/Bot/plugins/genshin/player_cards.py", line 66, in _fetch_user
    user = await self.client.http.fetch_user_by_uid(uid)
  File "/home/luoshuijs/anaconda3/envs/bot/lib/python3.9/site-packages/enkanetwork/http.py", line 132, in request
    err = ERROR_ENKA[response.status]
KeyError: 502
```

**Comment by luoshuijs** [comment]
Code failure point
https://github.com/mrwan200/EnkaNetwork.py/blob/ddfff47d4b9f7e35dfd6c97b5f01dae53ce8d212/enkanetwork/http.py#L131-L133
Recommend
```python3
 if _host == Config.ENKA_URL: 
     err = ERROR_ENKA.get(response.status)
     if err:
         raise err[0](err[1].format(uid=username)) 
     raise EnkaServerUnknown
```

**Comment by mrwan200** [comment]
Fixed: https://github.com/mrwan200/EnkaNetwork.py/commit/8d715563541ddfeb0aab1599c1ab3d3325cd3962

Thank you @luoshuijs to help this ❤️‍🔥

**Comment by luoshuijs** [comment]
@mrwan200 It is unnecessary to provide `None` as the default value when the key is not present in the dictionary as `get` implicitly returns `None`.
https://github.com/mrwan200/EnkaNetwork.py/blob/0f67dd16a22670278cc72fb0cd60bd041f47ee98/enkanetwork/http.py#L131
Of course you can ignore this problem if you like.

**Comment by mrwan200** [comment]
> @mrwan200 It is unnecessary to provide `None` as the default value when the key is not present in the dictionary as `get` implicitly returns `None`.
> 
> https://github.com/mrwan200/EnkaNetwork.py/blob/0f67dd16a22670278cc72fb0cd60bd041f47ee98/enkanetwork/http.py#L131
> 
> 
> Of course you can ignore this problem if you like.

Fixed 🙏
