### ISSUE TITLE
Pydantic 2.0 seems to broke the project

### ISSUE THREAD

**Issue by Donoma2** [mrwan200/EnkaNetwork.py#48]
Since pydantic 2.0 the project seems to not works anymore.
```pydantic_core._pydantic_core.ValidationError: 1 validation error for CharacterAsset
nameTextMapHash
  Input should be a valid string [type=string_type, input_value=712501082, input_type=int]
    For further information visit https://errors.pydantic.dev/2.0.3/v/string_type
```

When working with an oldest version of pydantic all works correctly.

Maybe you should precise to the requirements to not use pydantic 2.0: `pydantic<2`

**Comment by mrwan200** [comment]
Ok I will fix, Thank for advice
![Happy](https://media.tenor.com/Y-RLlSUzo7sAAAAS/klee-genshin-impact.gif)

**Comment by mrwan200** [comment]
Fixed: https://github.com/mrwan200/EnkaNetwork.py/actions/runs/5858768876/job/15883376318
