### ISSUE TITLE
character.element always returns Unknown

### ISSUE THREAD

**Issue by RealSosiso4ka** [mrwan200/EnkaNetwork.py#6]
After updating to version `1.2.9.dev1` (to avoid  «text map hash 147298547 is missing in assets» error) character.element always returns «Unknown».

**Comment by mrwan200** [comment]
Fixed https://github.com/mrwan200/EnkaNetwork.py/compare/77b5cadfd788...e3abc104b604

Please install using command this `pip install git+https://github.com/mrwan200/EnkaNetwork.py`
